### ISSUE TITLE
zabbix server access to agent-machine:10050 refused

### ISSUE THREAD

**Issue by lethe3000** [bhuisgen/docker-zabbix-coreos#3]
I launched zabbix agent on agent-machine with command:
```
docker run -d -p 20050:10050 -u 0 -c 1024 -m 64M --memory-swap=-1  -v /proc:/coreos/proc:ro -v /sys:/coreos/sys:ro -v /dev:/coreos/dev:ro     -v /var/run/docker.sock:/coreos/var/run/docker.sock     --name zabbix-coreos bhuisgen/docker-zabbix-coreos zabbix-server-ip coreos
```
but on the server side it tells:
Get value from agent failed: cannot connect to [[agent-machine]:10050]: [111] Connection refused

run *netstat -nlp* shows
```
tcp6       0      0 :::10050                :::*                    LISTEN      25350/docker-proxy
```

I tried to telnet shows:
```
$ telnet agent-machine 10050
Trying agent-machine...
Connected to agent-machine.
Escape character is '^]'.
Connection closed by foreign host.
```

could you help me how to troubleshoot with this issue? maybe some config error?

**Comment by sunsided** [comment]
Shouldn't that be `telnet agent-machine 20050` since you provided `-p 20050:10050`?
